language: go
go:
  - '1.12.x'
cache:
  directories:
  - $GOPATH/pkg/mod
install: .travis/install-pack.sh
script: GO111MODULE=on make test build acceptance
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_EVENT_TYPE = push && ($TRAVIS_BRANCH = master || $TRAVIS_BRANCH =~ ^v([0-9]+\.)+x$)
